version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pnpm-workspace:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/baret_docs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/contracts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
